export const racaOptions: string[] = [
  "Affenpinscher",
  "Cao de Castro Laboreiro",
  "Afghan Hound",
  "Cao de Crista Chines",
  "Airedale Terrier",
  "Cao de Santo Humberto (Bloodhound)",
  "Cao Fila de Sao Akita Americano",
  "Cao Leopardo da Catahoula",
  "American Bully",
  "Cao Lobo Tchecoslovaco",
  "American Pit Bull Terrier",
  "Cavalier King Charles Spaniel",
  "American Staffordshire Terrier",
  "Cesky Fousek",
  "Australian Caule Dog",
  "Cesky Terrier",
  "Australian Shepherd",
  "Chesapeake Bay Retriever",
  "Basenji",
  "Chihuahua",
  "Basset Alpino",
  "Chow Chow",
  "Basset Artesiano Normando",
  "Cimarron Uruguayo",
  "Basset Fulvo da Bretanha",
  "Cirneco do Etna",
  "Basset Hound",
  "Clumber Spaniel",
  "Beagle",
  "Cocker Spaniel Americano",
  "Beagle Harrier",
  "Cocker Spaniel Ingles",
  "Bearded Collie",
  "Collie Pelo Curto",
  "Bedlington Terrier",
  "Collie Pelo Longo",
  "Bernese Mountain Dog",
  "Coonhound Preto e Castanho",
  "Bichon Frise",
  "Coton de Tulear",
  "Bichon Havanês",
  "Dachshund Anão Pelo Curto",
  "Biewer Terrier",
  "Dachshund Anão Pelo Duro",
  "Boerboel",
  "Dachshund Anão Pelo Longo",
  "Bolognese",
  "Dachshund Kaninchen Pelo Curto",
  "Border Collie",
  "Dachshund Kaninchen Pelo Duro",
  "Border Terrier",
  "Dachshund Kaninchen Pelo Longo",
  "Borzoi",
  "Dachshund Standard Pelo Curto",
  "Boston Terrier",
  "Dachshund Standard Pelo Duro",
  "Bouvier des Flandres",
  "Dachshund Standard Pelo Longo",
  "Boxer",
  "Dálmata",
  "Braco Alemão Pelo Curto",
  "Dandie Dinmont Terrier",
  "Braco Alemão Pelo Duro",
  "Deerhound",
  "Braco de Auvergne",
  "Bretão",
  "Buldogue Campeiro",
  "Buldogue Francês",
  "Dogue Brasileiro",
  "Buldogue Serrano",
  "Dogue de Bordeaux",
  "Bull Terrier",
  "Elkhound Norueguês Cinza",
  "Bull Terrier Miniatura",
  "Entlebucher Cattle Dog",
  "Bulldog Americano",
  "Fila Brasileiro",
  "Bulldog Inglês",
  "Flat Coated Retriever",
  "Bullmastiff",
  "Fox Terrier Pelo Duro",
  "Fox Terrier Pelo Liso",
  "Cane Corso Italiano",
  "Foxhound Americano",
  "Cão d'Água Francês (Barbet)",
  "Foxhound Inglês",
  "Cão d'Água Frisado",
  "Galgo Árabe (Sloughi)",
  "Cão d'Água Português",
  "Galgo Espanhol",
  "Gascon Saintongeois",
  "Cão da Montanha dos Pireneus",
  "Golden Retriever",
  "Cão da Serra da Estrela",
  "Grande Munsterlander",
  "Cão das Montanhas do Atlas",
  "Griffon Azul da Gasconha",
  "Griffon Belga",
  "Griffon de Aponte de Pelo Duro Korthals",
  "Griffon de Bruxelas",
  "Griffon Nivernais",
  "Hokkaido",
  "Husky Siberiano",
  "Irish Soft Coated Wheaten Terrier",
  "Jack Russell Terrier",
  "Keeshond (Wolfspitz)",
  "Kelpie Australiano",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Komondor",
  "Korea Jindo Dog",
  "Kromfohrlander",
  "Kuvasz",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Laika da Sibéria Ocidental",
  "Lakeland Terrier",
  "Landseer",
  "Laufhund",
  "Leonberger",
  "Lhasa Apso",
  "Malamute do Alasca",
  "Maltes",
  "Mastiff Inglês",
  "Mastim dos Pireneus",
  "Mastim Espanhol",
  "Mastim Tibetano",
  "Mastino Napoletano",
  "Mudi",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Old English Sheepdog",
  "Olde English Bulldogge Brasileiro",
  "Otterhound",
  "Papillon",
  "Parson Russell Terrier",
  "Pastor Alemão",
  "Pastor Belga Groenendael",
  "Pastor Belga Laekenois",
  "Pastor Belga Malinois",
  "Pastor Belga Tervueren",
  "Pastor Branco Suíço",
  "Pastor da Anatólia",
  "Pastor da Ásia Central",
  "Pastor de Beauce",
  "Pastor de Brie",
  "Pastor de Shetland",
  "Pastor do Cáucaso",
  "Pastor Finlandês da Lapônia",
  "Pastor Holandês",
  "Pastor Iugoslavo",
  "Pastor Maremano Abruzes",
  "Pastor Polonês da Planície",
  "Shiba Inu",
  "Pastor Polonês de Tatra",
  "Shih Tzu",
  "Silky Terrier Australiano",
  "Patterdale Terrier",
  "Skye Terrier",
  "Pelado Mexicano",
  "Smoushond Holandês",
  "Pelado Peruano",
  "Spaniel Bretão",
  "Pequeno Cão Leão",
  "Spaniel d'Água Americano",
  "Pequeno Lebrel Italiano",
  "Spaniel d'Água Irlandês",
  "Pequeno Munsterlander",
  "Spaniel da Picardia",
  "Pequinês",
  "Spaniel Francês",
  "Perdigueiro Português",
  "Spaniel Japonês",
  "Petit Basset Griffon Vendeen",
  "Spaniel Tibetano",
  "Petit Brabançon",
  "Spinone Italiano",
  "Pharaoh Hound",
  "Spitz Alemão",
  "Pinscher Miniatura",
  "Spitz Finlandês",
  "Podengo Canário",
  "Spitz Japonês",
  "Podengo Ibicenco",
  "Springer Spaniel Inglês",
  "Podengo Português",
  "Stabyhoun",
  "Pointer Inglês",
  "Staffordshire Bull Terrier",
  "Poodle",
  "Terra Nova",
  "Porcelaine",
  "Terrier Alemão de Caça - JAGD",
  "Prague Ratter",
  "Terrier Australiano",
  "Pug",
  "Terrier Brasileiro",
  "Puli",
  "Terrier Escocês",
  "Pumi",
  "Terrier Irlandês",
  "Rafeiro do Alentejo",
  "Terrier Irlandês do Glen do Imaal",
  "Rastreador Brasileiro",
  "Terrier Preto da Rússia",
  "Retriever da Nova Escócia Duck Tolling",
  "Thai Ridgeback",
  "Rhodesian Ridgeback",
  "Tosa",
  "Rottweiler",
  "Toy Fox Terrier",
  "Saluki",
  "Vendeiro Pampeano",
  "Samoieda",
  "Vizsla (Braco Hungaro)",
  "São Bernardo",
  "Volpino Italiano",
  "Schipperke",
  "Weimaraner",
  "Schnauzer Gigante",
  "Welsh Corgi Cardigan",
  "Schnauzer Médio",
  "Welsh Corgi Pembroke",
  "Schnauzer Miniatura",
  "Welsh Springer Spaniel",
  "Sealyham Terrier",
  "Welsh Terrier",
  "Setter Gordon",
  "West Highland White Terrier",
  "Setter Irlandês Ruivo",
  "Wolfhound Irlandês",
  "Saluki Irlandês Vermelho e Branco",
  "Yakutian Laika",
  "Shar Pei",
  "Yorkshire Terrier",
  "Abissínio",
  "Angorá",
  "Balines",
  "Bengal",
  "Bobtail americano",
  "Bobtail japonês",
  "Bombay",
  "Burmês",
  "Chartreux",
  "Colorpoint de Pelo Curto",
  "Cornish Rex",
  "Curl Americano",
  "Devon Rex",
  "Himalaio",
  "Jaguatirica",
  "Javanes",
  "Korat",
  "LaPerm",
  "Maine Coon",
  "Manx",
  "Mau Egípcio",
  "Mist Australiano",
  "Munchkin",
  "Norueguês da Floresta",
  "Pelo Curto Americano",
  "Pelo Curto Brasileiro",
  "Pelo Curto Europeu",
  "Pelo Curto Inglês",
  "Persa",
  "Pixiebob",
  "Ragdoll",
  "Ocicat",
  "Russo Azul",
  "Sagrado da Birmânia",
  "Savannah",
  "Scottish Fold",
  "Selkirk Rex",
  "Siamês",
  "Siberiano",
  "Singapura",
  "Somali",
  "Sphynx",
  "Thai",
  "Tonquinês",
  "Toyger",
  "Usuri",
  "Sem Raça Definida (SRD)",
  "Sagui",
  "Furão",
  "Porco",
  "Porquinho da Índia",
  "Mini Porco",
  "Iguana",
  "Chinchila",
  "Cavalo",
  "Coelho",
  "Hamster",
  "Camundongo",
  "Esquilo",
  "Pentauro de Açúcar",
  "Outro",
  "Periquito",
  "Canário",
  "Calopsita",
  "Papagaio",
  "Galo/Galinha",
  "Peru",
  "Arara",
  "Mandarim",
  "Agapornis",
  "Pardal Doméstico",
  "Calafate",
  "Cardeal",
  "Curio",
  "Trinca Ferro",
  "Cacatua",
  "Cágado",
  "Tartaruga",
  "Jabuti",
  "Lagarto",
  "Cobra",
  "Sapo",
  "Perereca",
  "Salamandra",
  "Peixe Palhaço",
  "Tarântula",
  "Caramujo",
  "Caranguejo",
  "Sem Raça Definida",
  "Vira-lata",
  "Dogue Alemão",
  "Yorkshire Terrier",
]
